arm_joints:
  torso_lift_joint: 0.10

  head_pan_joint: 0.0
  head_tilt_joint: 0.0
  laser_tilt_mount_joint: 0.0

  l_gripper_motor_slider_joint: 0.0
  r_gripper_motor_slider_joint: 0.0

  l_shoulder_pan_joint: 0.0
  l_shoulder_lift_joint: 0.0
  l_upper_arm_roll_joint: 0.0
  l_elbow_flex_joint: 0.0
  l_forearm_roll_joint: 0.0
  l_wrist_flex_joint: 0.0
  l_wrist_roll_joint: 0.0

  r_shoulder_pan_joint: 0.0
  r_shoulder_lift_joint: 0.0
  r_upper_arm_roll_joint: 0.0
  r_elbow_flex_joint: 0.0
  r_forearm_roll_joint: 0.0
  r_wrist_flex_joint: 0.0
  r_wrist_roll_joint: 0.0

base:
  x: 0.0
  y: 0.0
  yaw: 0.0
